### ISSUE TITLE
Docker doesn't exit after the test

### ISSUE THREAD

**Issue by chunhongmao** [pmem/CacheLib#56]
Run test with docker built from 1b4a9864514f64d6fb9858f9ae2f1d75e41f0d3a, docker doesn't exit after the test is complete:

docker run --name cachelib_cachebench \
               --privileged --rm --shm-size=100G \
               --mount type=bind,source=/mnt/tmpfs_pmem,target=/mnt/tmpfs_pmem \
               --mount type=bind,source=$PWD,target=/result \
               -it cachelib_centos numactl --membind=0 taskset -c 0-23 ~/CacheLib/opt/cachelib/bin/cachebench \
               --json_test_config /result/config/$wl_name.json \
               -report_api_latency \
               -progress 1 \

**Expected behavior**
Docker shall exit after completing the test

**Desktop (please complete the following information):**
 - OS: CentOS

**Comment by igchor** [comment]
This should be fixed now
